"""SYSTEM — controllo OS runtime (generazioni, rebuild, profilo)

Endpoint per gestire SOLEM stesso dall'API: cambiare profilo, listare
generazioni NixOS, fare rebuild/rollback senza dover SSHare nella VM.

Endpoint:
  GET  /system/info                — info OS (kernel, hostname, profilo, uptime)
  GET  /system/generations         — lista generazioni NixOS + corrente
  POST /system/profile             — cambia profilo (scrive file + trigger rebuild)
  POST /system/rebuild              — trigger nixos-rebuild switch
  POST /system/rollback             — rollback alla generation precedente
  GET  /system/update/status        — stato auto-update (timer attivo?)
  POST /system/update/now           — trigger update manuale subito

ATTENZIONE: rebuild/rollback richiedono privilegi root nella VM. Step 0
usa sudo configurato in ai-freedom.nix (NOPASSWD per gavio user).
"""
from __future__ import annotations

import os
import platform
import subprocess
from datetime import datetime, timezone
from pathlib import Path
from typing import Literal

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field

router = APIRouter(prefix="/system", tags=["system"])

PROFILE_FILE = Path("/etc/nixos/solem-profile.nix")
NIXOS_CONFIG_DIR = Path("/etc/nixos")
PROFILE_VALUES = {"minimal", "developer", "creator", "server", "desktop"}


# ─── Schemas ──────────────────────────────────────────────────────────


class SystemInfo(BaseModel):
    hostname: str
    kernel: str
    arch: str
    python_version: str
    uptime_seconds: int
    profile: str
    nixos_version: str
    is_vm: bool


class Generation(BaseModel):
    number: int
    date: str
    is_current: bool


class GenerationsResponse(BaseModel):
    current: int
    total: int
    generations: list[Generation]


class ProfileChange(BaseModel):
    profile: Literal["minimal", "developer", "creator", "server", "desktop"]
    apply_now: bool = Field(False, description="True = rebuild switch subito; False = solo scrivi file (applica al prossimo manual rebuild)")


class RebuildResponse(BaseModel):
    success: bool
    new_generation: int | None = None
    log_tail: str
    duration_seconds: float


# ─── Endpoints info ──────────────────────────────────────────────────


@router.get("/info", response_model=SystemInfo)
async def system_info() -> SystemInfo:
    return SystemInfo(
        hostname=platform.node(),
        kernel=platform.release(),
        arch=platform.machine(),
        python_version=platform.python_version(),
        uptime_seconds=_read_uptime(),
        profile=_read_profile(),
        nixos_version=_read_nixos_version(),
        is_vm=_is_vm(),
    )


@router.get("/generations", response_model=GenerationsResponse)
async def list_generations() -> GenerationsResponse:
    try:
        out = subprocess.run(
            ["nix-env", "--list-generations", "--profile", "/nix/var/nix/profiles/system"],
            capture_output=True, text=True, timeout=10, check=True,
        )
    except (subprocess.SubprocessError, FileNotFoundError) as e:
        raise HTTPException(500, {"code": "nix_unavailable", "message": str(e)})

    gens: list[Generation] = []
    current = 0
    for line in out.stdout.strip().splitlines():
        parts = line.strip().split(maxsplit=3)
        if len(parts) < 3:
            continue
        try:
            number = int(parts[0])
        except ValueError:
            continue
        date = " ".join(parts[1:3])
        is_current = "(current)" in line
        if is_current:
            current = number
        gens.append(Generation(number=number, date=date, is_current=is_current))

    return GenerationsResponse(current=current, total=len(gens), generations=gens)


# ─── Endpoints control ────────────────────────────────────────────────


@router.post("/profile", response_model=RebuildResponse | dict)
async def change_profile(body: ProfileChange) -> dict:
    """Scrive nuovo profilo. Se apply_now=True, fa anche rebuild switch."""
    # Scrivi file inclusione esplicita del profilo
    content = f"# Auto-generated by /solem/system/profile API\n{{ ... }}: {{\n  solem.profile = \"{body.profile}\";\n}}\n"

    if not _can_write_profile():
        raise HTTPException(403, {
            "code": "profile_file_not_writable",
            "message": f"{PROFILE_FILE} non scrivibile. Verifica permessi.",
        })

    try:
        PROFILE_FILE.write_text(content)
    except OSError as e:
        raise HTTPException(500, {"code": "write_failed", "message": str(e)})

    if not body.apply_now:
        return {"profile_written": body.profile, "apply": False, "next_step": "Manual nixos-rebuild switch needed"}

    # Trigger rebuild
    return await rebuild()


@router.post("/rebuild", response_model=RebuildResponse)
async def rebuild() -> RebuildResponse:
    """Esegue `nixos-rebuild switch --flake .#solem-vm`."""
    start = datetime.now(timezone.utc)
    try:
        out = subprocess.run(
            ["sudo", "nixos-rebuild", "switch", "--flake", "/opt/solem-flake#solem-vm"],
            capture_output=True, text=True, timeout=900,
        )
    except subprocess.TimeoutExpired:
        raise HTTPException(504, {"code": "rebuild_timeout", "message": "Rebuild oltre 15 min"})
    except FileNotFoundError:
        raise HTTPException(500, {"code": "nixos_rebuild_missing"})

    duration = (datetime.now(timezone.utc) - start).total_seconds()
    log_tail = (out.stdout + out.stderr)[-2000:]

    new_gen = None
    if out.returncode == 0:
        try:
            g = subprocess.run(
                ["nix-env", "--list-generations", "--profile", "/nix/var/nix/profiles/system"],
                capture_output=True, text=True, timeout=5,
            )
            for line in g.stdout.splitlines():
                if "(current)" in line:
                    new_gen = int(line.strip().split()[0])
                    break
        except subprocess.SubprocessError:
            pass

    return RebuildResponse(
        success=(out.returncode == 0),
        new_generation=new_gen,
        log_tail=log_tail,
        duration_seconds=duration,
    )


@router.post("/rollback", response_model=dict)
async def rollback() -> dict:
    """Rollback alla generation precedente."""
    try:
        out = subprocess.run(
            ["sudo", "nixos-rebuild", "switch", "--rollback"],
            capture_output=True, text=True, timeout=300,
        )
    except subprocess.SubprocessError as e:
        raise HTTPException(500, {"code": "rollback_failed", "message": str(e)})
    return {
        "success": out.returncode == 0,
        "log_tail": (out.stdout + out.stderr)[-1000:],
    }


@router.get("/update/status", response_model=dict)
async def update_status() -> dict:
    """Stato del timer auto-update."""
    try:
        out = subprocess.run(
            ["systemctl", "is-active", "solem-update.timer"],
            capture_output=True, text=True, timeout=3,
        )
        active = out.stdout.strip() == "active"
    except subprocess.SubprocessError:
        active = False

    return {
        "auto_update_enabled": active,
        "config_file": "/etc/solem/update-config.json",
        "manual_trigger": "POST /solem/system/update/now",
    }


@router.post("/update/now", response_model=dict)
async def update_now() -> dict:
    """Trigger immediato di solem-update.service."""
    try:
        out = subprocess.run(
            ["sudo", "systemctl", "start", "solem-update.service"],
            capture_output=True, text=True, timeout=10,
        )
    except subprocess.SubprocessError as e:
        raise HTTPException(500, {"code": "trigger_failed", "message": str(e)})
    return {"triggered": True, "rc": out.returncode}


# ─── Helpers ──────────────────────────────────────────────────────────


def _read_uptime() -> int:
    try:
        return int(float(Path("/proc/uptime").read_text().split()[0]))
    except (OSError, ValueError):
        return 0


def _read_profile() -> str:
    try:
        return Path("/etc/solem/profile").read_text().strip()
    except OSError:
        return "minimal"


def _read_nixos_version() -> str:
    try:
        for line in Path("/etc/os-release").read_text().splitlines():
            if line.startswith("VERSION="):
                return line.split("=", 1)[1].strip().strip('"')
    except OSError:
        pass
    return "unknown"


def _is_vm() -> bool:
    try:
        out = subprocess.run(
            ["systemd-detect-virt"], capture_output=True, text=True, timeout=2, check=False,
        )
        return out.returncode == 0 and out.stdout.strip() != "none"
    except (subprocess.SubprocessError, FileNotFoundError):
        return False


def _can_write_profile() -> bool:
    try:
        return os.access(PROFILE_FILE.parent, os.W_OK)
    except OSError:
        return False
